figure;
[a,map]=imread('stopsgn.jpg');
[h,w,~]=size(a); 
g=ones(110,500,3).*255;
for j=1:3;g(11:(h+10),11:(w+10),j)=a(:,:,j);end;
g(g>240)=158;
g=double(g)./255;

H = uicontrol('Style', 'PushButton', ...
              'String', 'Stop', ...
              'Position',[20,20,500,110],...
              'FontSize',50,...
              'FontWeight','Bold',...
              'Callback', 'delete(gcbf)',...
              'CData',g);
