mex -I/usr/local/include ...
    -I/usr/include ...
     tessWrapper.cpp ...
    -L/usr/local/lib ...
    -L/usr/lib64 ...
    -ltesseract ...
    -lmx ...
    -lmex ...
    -llept ...
    -lgomp ...
    -lclstm ...
    -llept

